export const jobChurnTableColumns = [
  {
    name: "Date",
    label: "Date",
    field: "Date",
    required: false,
    align: "left",
    headerStyle: "width: 50px",
    headerClasses: "table-header",
  },
  {
    name: "Open Jobs",
    label: "Open Jobs",
    field: "Open Jobs",
    required: false,
    align: "left",
    headerStyle: "width: 50px",
    headerClasses: "table-header",
  },
  {
    name: "Completed Jobs",
    label: "Completed Jobs",
    field: "Compelted Jobs",
    required: false,
    align: "left",
    headerStyle: "width: 50px",
    headerClasses: "table-header",
  },
  {
    name: "Average Days Open",
    label: "Average Days Open",
    field: "Avereage Days - Open Jobs",
    required: false,
    align: "left",
    headerStyle: "width: 50px",
    headerClasses: "table-header",
  },
];
