export const jobTableColumns = [
  {
    name: "jobNumber",
    label: "Job #",
    field: "jobNumber",
    required: true,
    align: "left",
    sortable: true,
    sort: (a, b, rowA, rowB) => parseInt(a, 10) - parseInt(b, 10),
    sortOrder: "ad",
    headerStyle: "width: 50px",
    headerClasses: "table-header",
  },
  {
    name: "required",
    label: "Job Date",
    field: "required",
    required: true,
    align: "left",
    sortable: true,
    sort: (a, b, rowA, rowB) => parseInt(a, 10) - parseInt(b, 10),
    sortOrder: "ad",
    headerStyle: "width: 50px",
    headerClasses: "table-header",
  },
  {
    name: "registration",
    label: "Registration",
    field: "registration",
    required: true,
    align: "left",
    sortable: true,
    sort: (a, b, rowA, rowB) => parseInt(a, 10) - parseInt(b, 10),
    sortOrder: "ad",
    headerStyle: "width: 50px",
    headerClasses: "table-header",
  },
  {
    name: "vehicleType",
    label: "Vehicle Type",
    field: "vehicleType",
    required: true,
    align: "left",
    sortable: true,
    sort: (a, b, rowA, rowB) => parseInt(a, 10) - parseInt(b, 10),
    sortOrder: "ad",
    headerStyle: "width: 50px",
    headerClasses: "table-header",
  },
  {
    name: "status",
    label: "Job Status",
    field: "status",
    required: true,
    align: "left",
    sortable: true,
    sort: (a, b, rowA, rowB) => parseInt(a, 10) - parseInt(b, 10),
    sortOrder: "ad",
    headerStyle: "width: 50px",
    headerClasses: "table-header",
  },
  {
    name: "jobType",
    label: "Job Type",
    field: "jobType",
    required: true,
    align: "left",
    sortable: true,
    sort: (a, b, rowA, rowB) => parseInt(a, 10) - parseInt(b, 10),
    sortOrder: "ad",
    headerStyle: "width: 50px",
    headerClasses: "table-header",
  },
  {
    name: "distance",
    label: "Mileage",
    field: "distance",
    required: true,
    align: "left",
    sortable: true,
    sort: (a, b, rowA, rowB) => parseInt(a, 10) - parseInt(b, 10),
    sortOrder: "ad",
    headerStyle: "width: 50px",
    headerClasses: "table-header",
  },
  {
    name: "supplier",
    label: "Supplier",
    field: "supplier",
    required: true,
    align: "left",
    sortable: true,
    sort: (a, b, rowA, rowB) => parseInt(a, 10) - parseInt(b, 10),
    sortOrder: "ad",
    headerStyle: "width: 50px",
    headerClasses: "table-header",
  },
  {
    name: "customer",
    label: "Customer",
    field: "customer",
    required: true,
    align: "left",
    sortable: true,
    sort: (a, b, rowA, rowB) => parseInt(a, 10) - parseInt(b, 10),
    sortOrder: "ad",
    headerStyle: "width: 50px",
    headerClasses: "table-header",
  },
  {
    name: "itemDescription",
    label: "Work Description",
    field: "itemDescription",
    required: true,
    align: "left",
    sortable: true,
    sort: (a, b, rowA, rowB) => parseInt(a, 10) - parseInt(b, 10),
    sortOrder: "ad",
    headerStyle: "width: 50px",
    headerClasses: "table-header",
  },
  {
    name: "labour",
    label: "Labour Cost",
    field: "labour",
    required: true,
    align: "left",
    sortable: true,
    sort: (a, b, rowA, rowB) => parseInt(a, 10) - parseInt(b, 10),
    sortOrder: "ad",
    headerStyle: "width: 50px",
    headerClasses: "table-header",
  },
  {
    name: "parts",
    label: "Parts Cost",
    field: "parts",
    required: true,
    align: "left",
    sortable: true,
    sort: (a, b, rowA, rowB) => parseInt(a, 10) - parseInt(b, 10),
    sortOrder: "ad",
    headerStyle: "width: 50px",
    headerClasses: "table-header",
  },
  {
    name: "cost",
    label: "Total Cost",
    field: "cost",
    required: true,
    align: "left",
    sortable: true,
    headerStyle: "width: 50px",
    headerClasses: "table-header",
  },
  {
    name: "recharge",
    label: "Recharge Amount",
    field: "recharge",
    required: true,
    align: "left",
    sortable: true,
    sort: (a, b, rowA, rowB) => parseInt(a, 10) - parseInt(b, 10),
    sortOrder: "ad",
    headerStyle: "width: 50px",
    headerClasses: "table-header",
  },
  {
    name: "daysVOR",
    label: "Days VOR",
    field: "daysVOR",
    required: true,
    align: "left",
    sortable: true,
    sort: (a, b, rowA, rowB) => parseInt(a, 10) - parseInt(b, 10),
    sortOrder: "ad",
    headerStyle: "width: 50px",
    headerClasses: "table-header",
  },
];
